### ISSUE TITLE
virtualbox 만 사용하여 provision.sh 를 할 경우 문제점들

### ISSUE THREAD

**Issue by iz4blue** [codeforseoul/FdAS#31]
virtualbox 위에서 ubuntu-14.01.1-server-i386 를 사용해서 README.md 에서 설명한 것처럼 되는지 따라가 봅니다.

* provision.sh 수행이후 /etc/apt/source.list 에서 ftp.daum.net 으로 변경되어야 하는 것이 kr.ftp.daum.net 이 되어 있음
* .sh 파일들은 +x 권한이 있어도 될 것 같은데 실행권한들이 없네요? 일부러 그러신건지?
* /dev/null 보다는 ./tmp/install-log.txt 파일을 만들어서 설치 내용을 기록에 남기는 것도 좋을 듯?
* 어떤 이유인지 모르겠으나 provision.sh 를 수행이후에는 apt-get install npm 이 수많은(?) 의존성에 걸려서 설치 되지 않음
```
The following packages have unmet dependencies:
 npm : Depends: nodejs but it is not going to be installed
       Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
       Depends: node-ansi but it is not going to be installed
       Depends: node-archy but it is not going to be installed
       Depends: node-block-stream but it is not going to be installed
       Depends: node-fstream (>= 0.1.22) but it is not going to be installed
       Depends: node-fstream-ignore but it is not going to be installed
       Depends: node-github-url-from-git but it is not going to be installed
       Depends: node-glob (>= 3.1.21) but it is not going to be installed
       Depends: node-graceful-fs (>= 2.0.0) but it is not going to be installed
       Depends: node-inherits but it is not going to be installed
       Depends: node-ini (>= 1.1.0) but it is not going to be installed
       Depends: node-lockfile but it is not going to be installed
       Depends: node-lru-cache (>= 2.3.0) but it is not going to be installed
       Depends: node-minimatch (>= 0.2.11) but it is not going to be installed
       Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
       Depends: node-gyp (>= 0.10.9) but it is not going to be installed
       Depends: node-nopt (>= 2.1.1) but it is not going to be installed
       Depends: node-npmlog but it is not going to be installed
       Depends: node-once but it is not going to be installed
       Depends: node-osenv but it is not going to be installed
       Depends: node-read but it is not going to be installed
       Depends: node-read-package-json (>= 1.1.0) but it is not going to be installed
       Depends: node-request (>= 2.25.0) but it is not going to be installed
       Depends: node-retry but it is not going to be installed
       Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
       Depends: node-semver (>= 2.1.0) but it is not going to be installed
       Depends: node-sha but it is not going to be installed
       Depends: node-slide but it is not going to be installed
       Depends: node-tar (>= 0.1.18) but it is not going to be installed
       Depends: node-which but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by iz4blue** [comment]
음... vagrent 로 따라가도 다음과 같이 에러가 나네요.
```
==> default: ###### 2 Dependencies - nodejs ######
==> default: ###### 2 Dependencies - nodejs modules ######
==> default: npm ERR! Error: EACCES, mkdir '/home/vagrant/.npm/async/0.1.22'
==> default: npm ERR!  { [Error: EACCES, mkdir '/home/vagrant/.npm/async/0.1.22']
==> default: npm ERR!   errno: 3,
==> default: npm ERR!   code: 'EACCES',
==> default: npm ERR!   path: '/home/vagrant/.npm/async/0.1.22',
==> default: npm ERR!   parent: 'grunt' }
==> default: npm ERR!
==> default: npm ERR! Please try running this command again as root/Administrator.
==> default:
==> default: npm ERR! System Linux 3.13.0-44-generic
==> default: npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
==> default: npm ERR! cwd /vagrant
==> default: npm ERR! node -v v0.10.35
==> default: npm ERR! npm -v 1.4.28
==> default: npm ERR! path /home/vagrant/.npm/async/0.1.22
==> default: npm ERR! code EACCES
==> default: npm ERR! errno 3
==> default: npm ERR! stack Error: EACCES, mkdir '/home/vagrant/.npm/async/0.1.22'
==> default: npm
==> default:
==> default: ERR!
==> default:
==> default: not ok
==> default:  code 0
==> default: supervisor (7538) logging to 'supervisor.log'
==> default: INFO strong-agent API key not found, StrongOps dashboard reporting disabled.
==> default: Generate configuration with:
==> default:     npm install -g strongloop
==> default:     slc strongops
==> default: See http://docs.strongloop.com/strong-agent for more information.
==> default: supervisor 7538 detached process 7544, output logged to 'supervisor.log'
MacBook-Pro:fads iz4blue$ ls
```

**Comment by iz4blue** [comment]
이제는 이런 에러가...

```
vagrant@vagrant-ubuntu-trusty-32:/vagrant$ slc run
INFO strong-agent API key not found, StrongOps dashboard reporting disabled.
Generate configuration with:
    npm install -g strongloop
    slc strongops
See http://docs.strongloop.com/strong-agent for more information.
supervisor running without clustering (unsupervised)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at Server._listen2 (/vagrant/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:71:23)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
```

**Comment by mozodev** [comment]
이건 포트가 사용중일때 나오는 에러인데 음... 확인해보세요.. 그리고 지금 프로비저닝 쉘스크립트 수정 중입니다. 테스트 거의 다 됐으니까 곧 푸시할께요~

**Comment by iz4blue** [comment]
아싸 기다리고 있겠습니다 :)

**Comment by iz4blue** [comment]
음 이제는 아이템이 보이질 않네요?
![screen shot 2015-01-29 at 1 06 26 pm](https://cloud.githubusercontent.com/assets/979297/5952368/23da7126-a7b9-11e4-97d8-666f10ffbe80.png)

**Comment by mozodev** [comment]
https://github.com/codeforseoul/FdAS/wiki/dev-notes

닫습니다~
